language: php
php:
  - '5.5'
  - '5.6'
  - '7.2'
  - hhvm # on Trusty only
  - nightly
os: windows










# before_script:
#   - composer install --no-interaction

script:
  # - vendor/bin/phpunit
  # - phpunit --configuration phpunit.xml



# ----------------------
#   version: 2

# jobs:
#   build:
#     docker:
#       - image: circleci/php:7.1.5-browsers
#     working_directory: ~/wu2018
#     steps:
#       - checkout
#       - run: php --ini