sudo: required

language: php
php:
  - '5.5'
  - '5.6'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

branches:
  only:
    master

# install:
#     - composer update phpunit/phpunit    # added
#     - composer require satooshi/php-coveralls:^1.0 --dev

# before_script:
#    - composer install --no-interaction

script:
   - vendor/bin/phpunit
   - phpunit --configuration phpunit.xml









# before_script:
#   - composer install --no-interaction

script:
  # - vendor/bin/phpunit
  # - phpunit --configuration phpunit.xml



# ----------------------
#   version: 2

# jobs:
#   build:
#     docker:
#       - image: circleci/php:7.1.5-browsers
#     working_directory: ~/wu2018
#     steps:
#       - checkout
#       - run: php --ini