sudo: required

language: php
php:
  # - '5.5'
  # - '5.6'
   - 7.1.5
   - 7.2
   - hhvm # on Trusty only
   - nightly

branches:
  only:
    master



before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev


script:
   - vendor/bin/phpunit
   - phpunit --configuration phpunit.xml
   - npm install # install node module
   - npm run build # build project
   - echo “Deploy!!”

notifications:
email: false

install:
  - npm install -g firebase-tools # install firebase-cli

deploy:
  provider : firebase
  token:
    secure: 1/Maizr4AKZaSIyFdV38ZBIVfrev6s5kOod5wBFEur4Fo

after_success:
  - firebase deploy — project projectId — token $FIREBASE_TOKEN.
  - firebase use --token ${FIREBASE_TOKEN} # set firebase token
  - firebase use --add ${PROJECT_ID} # set current project
  #- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" # deploy project









# before_script:
#   - composer install --no-interaction

script:
  # - vendor/bin/phpunit
  # - phpunit --configuration phpunit.xml



# ----------------------
#   version: 2

# jobs:
#   build:
#     docker:
#       - image: circleci/php:7.1.5-browsers
#     working_directory: ~/wu2018
#     steps:
#       - checkout
#       - run: php --ini